FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# QuotED API

## Quotes Collection [/quotes]

### Get random quote of defined text complexity [POST /quotes/random]

+ Request (application/json)

        {
            "minComplexity": 0.123234,
            "maxComplexity": 0.678242,
            "search": "nigger",
            "exclude": [
                123,
                32525323,
                2354235
            ]
        }

+ Response 200 (application/json)

        {
            "quote": "Never trust a nigger: their minds and hair are full of kinks in equal measure.",
            "author": "White Guy",
            "book": "Stupid Ideas",
            "complexity": 0.2314125,
            "id": 123124124
        }
